#!/usr/bin/env bash
# installs nginx
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo /etc/init.d/nginx reload
curl -s http://localhost:80/
