#!/usr/bin/env bash
# installs nginx
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo kill -s HUP $(pidof nginx)
curl -s http://localhost:80/
