#!/usr/bin/env bash
# script configuring a server to have a customized pesponse header

sudo apt-get update
sudo apt-get install -y nginx

# index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirection
var_redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com permanent;"

sudo sed -i "s/server_name _;/$var_redirect/" /etc/nginx/sites-enabled/default

# Error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom http response header
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

sudp sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# syntax error checking
sudo nginx -t

# restart service
sudo service nginx restart
