#!/usr/bin/env bash
# script checking if container is listening on port 80
sudo apt-get update
if ! command -V nginx > /dev/null 2>&1; then
	sudo apt-get install nginx -y
fi
nginx_status=$(sudo systemctl is-active nginx)
if [ "$nginx_status" != "active" ]; then
	sudo service nginx start
fi
if sudo ngnx -t &> /dev/null; then
	stat=$(sudo netstat -lpn | grep ':80 ')
	if [ -z "$stat" ]; then
		sudo ufw allow 80
	fi
fi
