#!/usr/bin/env bash
# script displaying "Best School" 10 times
# on the forth print it prints "bad luck" instead
# on the eigth print it prints "good luck" instead
i=1
while [[ $i -le 10 ]]
do
if [[ $i -eq 4 ]]
then
echo bad luck
elif [[ $i -eq 8 ]]
then
echo good luck
else
echo Best School
fi
((i++))
done
