#!/usr/bin/bash
# Script that prints numbers 1 - 20 excluding various superstitious numbers
i=1
while [[ $i -le 20 ]]
do
echo $i
case $i in
	4)
		echo bad luck from China
		;;
	9)
		echo bad luck from Japan
		;;
	17)
		echo bad luck from Italy
		;;
	*)
		;;
esac
((i++))
done
