#!/usr/bin/env bash
# Script that prints numbers 1 - 20 excluding various superstitious numbers
i=1
while [[ $i -le 20 ]]
do
if [[ $i -eq 4 || $i -eq 9 || $i -eq 17 ]]
then
	echo $i
fi
case $i in
	4)
		echo bad luck from China
		;;
	9)
		echo bad luck from Japan
		;;
	17)
		echo bad luck from Italy
		;;
	*)
		echo $i
		;;
esac
((i++))
done
